# Generated by Django 4.0.5 on 2023-01-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('product_features', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Product Descriptions',
                'ordering': ['product_category'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('task_status', models.CharField(max_length=200)),
                ('task_created_date', models.DateTimeField(auto_now_add=True)),
                ('task_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Task Details',
                'ordering': ['task_created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField()),
                ('product_collected_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_scrapper.product')),
            ],
        ),
    ]
