# Generated by Django 4.0.5 on 2023-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_features',
            field=models.TextField(blank=True),
        ),
    ]
