# Generated by Django 4.0.5 on 2023-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.TextField(blank=True),
        ),
    ]
