# Generated by Django 4.0.5 on 2023-01-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_images',
        ),
    ]
