# Generated by Django 4.0.5 on 2023-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0007_alter_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.TextField(blank=True),
        ),
    ]
