# Generated by Django 4.0.5 on 2023-01-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0008_alter_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresources',
            name='product_url',
            field=models.URLField(max_length=950),
        ),
    ]
