# Generated by Django 4.0.5 on 2023-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0009_alter_productresources_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresources',
            name='product_url',
            field=models.TextField(),
        ),
    ]
